### ISSUE TITLE
[Important] Update F-Droid to 1.16.3 to prevent serious data loss bug

### ISSUE THREAD

**Issue by TheLastProject** [lineageos4microg/android_vendor_partner_gms#21]
Hey team,

I recently updated from LineageOS for microG 19.1 to 20. Doing this caused F-Droid to lose all apps and ability to update.

After debugging with the rest of the F-Droid team, we figured out that this is a bug introduced in F-Droid 1.16, where a major Android version upgrade will put the database into an incorrect state: https://gitlab.com/fdroid/fdroidclient/-/merge_requests/1210. We tagged a new release (1.16.3) which fixes this bug.

While we don't know if your ROM updates F-Droid installations on OS upgrades, but if it does, it would be great if you could include 1.16.3 as soon as it is available (I will notify you when that is, we're currently busy with the build and signing process). We believe that, if 1.16.3 is installed before the first time F-Droid is launched after a major Android version update it should no longer put its database into an incorrect state, therefore allowing users to upgrade from LineageOS 19.1 to 20 without breaking F-Droid.

Kind regards,
Sylvia van Os
(F-Droid Contributor)

**Comment by TheLastProject** [comment]
1.16.3 is now available! Please update as soon as you get a chance. Thank you!

**Comment by bananer** [comment]
Thanks for reaching out, this does indeed seem urgent. F-Droid is updated automatically daily, but the builds for this month were already started. I manually triggered the F-Droid update (00b5731) and restarted the builds, so the fixed version will be included as fast as possible.

**Comment by bananer** [comment]
Since F-Droid 1.16 was only released two weeks ago, I also deleted all builds from the previous round. No more builds with the faulty F-Droid version will be distributed, new builds coming up soon!

**Comment by TheLastProject** [comment]
Thank you for the quick response and care!

**Comment by mll0** [comment]
Hi,

I'm at loss as to where to report what could be bugs on LOS MigroG. And I was shown this thread that _could_ be related to my problem. Since it's been 4 days that I can't boot my main phone, I'm reaching some desperate state, so even if my problem isn't related to the Fdroid bug reported in the OP, I'd really appreciate if you could point me to a place where I'd get some support.

On my main phone (a Fairphone 3) that was on LOS 19 microG, I dirty flashed LOS 20 microG that went out about 4 days ago (https://download.lineage.microg.org/builds/full/FP3/lineage-20.0-20230403-microG-FP3.zip). The reboot went smoothly. However, the install of updated apps through Aurora would fail (I didn't test Fdroid then).

Thinking a reboot might solve this, I went for it, and alas, I get a bootloop (the animated LOS logo stays for a long time, eventually leading to a reboot). Reapplying the LOS4MG upgrade doesn’t fix anything. And today I realise that the build was withdrawn, and no other LOS4MG v20 is available yet (https://download.lineage.microg.org/FP3/). Is that withdrawal related to my issue? Any idea of what could be wrong? Is there any way to revert to a functioning phone (I fear that dirty flashing the latest LOS4MG 19.1 image would make things worse)?

**Comment by Exodusnick** [comment]
You will certainly get help here
https://forum.xda-developers.com/t/lineageos-for-microg.3700997/

**Comment by mll0** [comment]
> You will certainly get help here https://forum.xda-developers.com/t/lineageos-for-microg.3700997/

Alas, I got none there, nor in any other place. I fear I have to wipe & flash. Too bad for my Signal history, which I didn't backup before. :/

**Comment by petefoth** [comment]
Current version of F-Droid 1.19.1

Closing this issue
