### ISSUE TITLE
com.google.android.maps.jar module reference broken

### ISSUE THREAD

**Issue by SebiderSushi** [lineageos4microg/android_vendor_partner_gms#3]
https://github.com/lineageos4microg/android_vendor_partner_gms/blob/926ef35420d1c497665788657ea7e190117f39c7/products/gms.mk#L7

https://github.com/lineageos4microg/android_vendor_partner_gms/blob/926ef35420d1c497665788657ea7e190117f39c7/com.google.android.maps/Android.mk#L12

**Comment by bananer** [comment]
That looks very much like a mistake I made when creating `gms.mk`, thanks for reporting! Did you notice any errors or missing functioniality because of it?

The affected package is filling in for GMaps API v1, which was deprecated in 2012 and no more API keys were issued since 2013. I'm inclined to think there is no more value in keeping it around anyways.

**Comment by SebiderSushi** [comment]
That is true; i am not aware of any currently reproducible issues with missing MapsAPIv1

All i have is a faint memory of when i still installed MicroG by using a Magisk Module about 2-3 years ago. I was using my own custom module and on one occasion i believe i had to add the maps.jar to it. I do not remember the specific reason but i do believe that i wouldn't even have noticed that i forgot to include it if everythig had worked without it.

My best guess is even if it's deprecated, legacy apks built years ago may definitely still be around and i can easily imagine that every other power user has this one ancient apk they keep around because it "just does what they want". I for one use a couple of apps that were built years ago, the only difference is that those are from F-Droid and wouldn't use any google services anyway.

**Comment by bananer** [comment]
Since this has been broken for the last six weeks and power user complained about their ancient apk being broken, it should be safe to remove. https://github.com/lineageos4microg/android_vendor_partner_gms/commit/ba80049035fe79670d68abf8971abc650c0f5a79

Thanks again for reading our code so carefully!

**Comment by SebiderSushi** [comment]
okay :)
