### ISSUE TITLE
Stop shipping FDroidPrivilegedExtension

### ISSUE THREAD

**Issue by grote** [lineageos4microg/android_vendor_partner_gms#33]
The shipped F-Droid version now uses the `SessionInstaller` and if it is the installer/update owner of an app, it can update that app without user confirmation, thus do automatic background updates. User confirmation is only required for initial install and uninstall (arguably a good security feature), as well as when another app had installed the app to update.

So the privileged extension isn't really needed anymore, except no user prompts at all are wanted.

**Comment by petefoth** [comment]
This was raised previously in the ci/cd project issue tracker:

https://github.com/lineageos4microg/docker-lineage-cicd/issues/568

The reasons for continuing to ship it are explained in [this comment to that issue](https://github.com/lineageos4microg/docker-lineage-cicd/issues/568#issuecomment-1936914360)

Those reasons haven't changed: some users will still want to build 18.1 and earlier builds, and will want the the 'unattended updates' functionality. We should support that, and for that we need the Privileged Extension.

So this isn't a bug, and won't be 'fixed'. I'll close it sometime soon unless anyone comes up with any fresh arguments

**Comment by grote** [comment]
Sure, not a bug, just a suggestion. Sounds like it could get removed once you don't ship LineageOS 18 anymore. It was already sun-setted upstream: https://lineageos.org/Sunsetting-LineageOS-18.1/

**Comment by petefoth** [comment]
We don't ship 18.1 builds any more either, but one of the purposes of this project and its Docker image it to allow others to easily make builds (of LineaageOS for microG or 'vanilla' LineageOS without microG) for a number of different devices. As builds of earlier Android versions (19.1 and earlier) are no longer readily available from official download sites, 'build it yourself' is often the only option looking for a build to run on devices which are no longer supported. 

I'll close this issue anyway, as we wonlt be making any changes along these lines. Thanks for the report though.

**Comment by licaon-kter** [comment]
Once F-Droid 2.0 is out the Priv Ext would not be used any more, for Android 7 and up, fyi.

**Comment by petefoth** [comment]
Re-opening: I think we ***can*** stop shipping the Privileged extension once we are shipping version 2.0 of the F-Droid app - see #100

**Comment by eighthave** [comment]
I would love feedback from LineageOS-for-microG on whether you'd prefer to keep shipping F-Droid Privileged Extension (FPE) or not.  The "session" API does provide a lot more of what FPE offers, but not yet everything.  There are somethings that the session API will never provide that can come from FPE.  We paused development of FPE to focus on what was possible with the session API. It does a lot and Google is improving it. It is clear that the session API is not as well maintained as the API that FPE uses since Google itself does not use the session API.  PlayServices always has privileged access.

We have applied for a grant to do a development round on FPE to provide auditing features similar to what PlayServices provides (IMHO better) and some novel controls over installation for heightened security needs.  That could still happen if we don't get the grant, but someone would have to step up to do the work.

**Comment by petefoth** [comment]
> I would love feedback from LineageOS-for-microG on whether you'd prefer to keep shipping F-Droid Privileged Extension (FPE) or not.

My perspective (as 'lead' maintainer of the LineageOS for microG  project) is that:
- the project goal is to ship a ROM that includes
	1. LineageOS ;
	2. the microG components;
	3. a means of installing FOSS apps and keeping them updates, preferably automaticall;y
- FDroid v1 (which we currently ship) achieves the automatic updates part of iii for most versions of Android. We include FPE to achieve 3 for older - but still buildable (maybe) - versions with our Docker image.
- FDroid v2 will - as I understand it - achieve all of iii, including the automatic updates part, for all Android version
- Once we start shipping FDroid v2, we have no reason to also ship FPE, so we plan to stop including it.
- You say
> There are somethings that the session API will never provide that can come from FPE

  I have no idea what those things are, and whether we need them to achieve our project goals. I suspect that we don't because I ***believe*** FDroid v2 will do everything that we need. The project is not really in the business of providing new features*, so unless I have missed something important, I think we will be happy to stop shipping FPE when FDroid v2 is included.

 `*` Though I am sometimes tempted to include Aurora Store, and stub Google apps to allow Android Auto to work without resorting to Magisk or `adb` command line magic. I hope to continue resisting that temptation 😄

**Comment by licaon-kter** [comment]
> FDroid v2 will - as I understand it - achieve all of iii, including the automatic updates part, for all Android version

slight correction, "for Android 12 and later"

**Comment by eighthave** [comment]
Thanks for the feedback.  As for your impression of iii), the installer setup in F-Droid 2.0 handles something like 90% of the install/update cases that FPE handles.  So it is viable for you to ship without FPE.  We've seen quite a few bugs in this "session" installer API that make the user experience suffer quite a bit.  Google Play does not use this API, Google was basically forced by anti-trust actions to provide it.  So it is in Google's interest to leave it buggy.  That means in the not-too-distant future, we might start work on FPE again.  In that case, I'll reach out again.

Thank you for resisting the temptation to include support for proprietary app stores!  There are projects who are starting work on making a lot more proprietary apps available via fdroid repos, so we hope that soon, the F-Droid client will cover most of our users' use cases for Aurora Store.

**Comment by petefoth** [comment]
> > FDroid v2 will - as I understand it - achieve all of iii, including the automatic updates part, for all Android version
> 
> slight correction, "for Android 12 and later"

which implies that we still need it for 18.1 builds and earlier. In an earlier comment I wrote
>  We don't ship 18.1 builds any more either,

That is no longer the case: we **_do_** make 18.1 builds ,every few months when there are enough back-ported changes to make it worthwhile.

@eighthave, you wrote
> As for your impression of iii), the installer setup in F-Droid 2.0 handles something like 90% of the install/update cases that FPE handles. So it is viable for you to ship without FPE.  

The specific update case for which I think we ***do*** still need to ship FPE is automatic unattended updates ***for 18.1 and earlier versions***. Does the installer setup in F-Droid 2.0 support that use-case? If not, then I think we will continue to ship FPE, though we could change [our `gms.mk`](https://github.com/lineageos4microg/android_vendor_partner_gms/blob/master/products/gms.mk) to only add it to `PRODUCT_PACKAGES` if Android version is less than 12.

**Comment by licaon-kter** [comment]
Users on Android 7 and later will be updated to Client 2.0 that won't use FPE.

Keeping FPE makes sense ONLY if users decide to stay with Client 1.23.2.

**Comment by licaon-kter** [comment]
> We've seen quite a few bugs in this "session" installer API that make the user experience suffer quite a bit. Google Play does not use this API, Google was basically forced by anti-trust actions to provide it. So it is in Google's interest to leave it buggy.

Sure, we'll work around, we'll report, they'll fix. They've done this before, and so did we.

**Comment by eighthave** [comment]
I'm optimistic that we can find resources to support FPE in 2.0, but it could be months.  I think supporting old devices is important.  I'll keep you posted.  If you know anyone who wants to work on this, I'd be happy to help them.

**Comment by eighthave** [comment]
So I think it makes sense for you to still ship FPE like you do, but F-Droid 2.x releases won't use it until support has been implemented there.

**Comment by petefoth** [comment]
> Users on Android 7 and later will be updated to Client 2.0 that won't use FPE.

_**Only**_ if Client 2.0 will support automatic unattended updates for versions before Android 12. If not, then we will continue to ship F-Droid 1 and the FPE, for those versions at least (and maybe for all versions - newer versions, when unattended updates **_are_** supported by Client 2.0, can then pick up Client 2.0 via the normal update mechanism).

**Comment by licaon-kter** [comment]
Users will see app updates, they'll install the updates and be happy.

One of the updates will be for F-Droid client.

:)

**Comment by petefoth** [comment]
> Users will see app updates, they'll install the updates and be happy

The **_whole point_** of FPE is that users don't have to install them - they are installed ***automatically, with no user input***. That functionality is not supported by F-Droid 1 or 2 for android versions lower than 12 **_without_** FPE. So will continue to ship FPE for those versions

**Comment by licaon-kter** [comment]
Are we lost in translation? :)

I'm not talking about FPE now, please focus on apps. Apps will get updated, you know, like Calendar, VLC and XMPP clients and whatever else users have installed. Users will update them, manually or not, not the point.

One such app is F-Droid itself, it will be updated along with the other user apps.

Unless users on Android 7 and later read this discussion (most won't) and decide to skip updating F-Droid client (we have a per-app setting to skip), then the  update to 2.0 will just be another app update.

I bet many will be glad to get the modern looking, Material You themed 2.0 update.

**Comment by petefoth** [comment]
> One such app is F-Droid itself, it will be updated along with the other user apps.
> 
> Unless users on Android 7 and later read this discussion (most won't) and decide to skip updating F-Droid client (we have a per-app setting to skip), then the update to 2.0 will just be another app update.

And if 2.0 **_does not_** support unattended app updates for Android versions less than 12 - whether via FPE or some other mechanism - we have a problem. I don't want users of those Android versions to 'upgrade' to a version that has less functionality than the current version. So I am waiting to hear from @eighthave whether or not 2.0 _**does**_ support unattended app updates for Android versions less than 12. When we find that out we can make a decision on how to proceed

**Comment by licaon-kter** [comment]
Imagine there are no funds and no one working at this for the next 6 months. How will you proceed? You'll block at system level the install of `org.fdroid.fdroid` with versionCode 2000000 ?

**Comment by petefoth** [comment]
> How will you proceed?

I don't know. Which is why I am waiting on @eighthave's reply. When I have the reply I will work out what needs too happen to avoid shipping a version of F-Droid with regressions.

**Comment by licaon-kter** [comment]
F-Droid are shipping F-Droid (updates). :)

You can still include 1.23.2 in the base.

**Comment by eighthave** [comment]
@licaon-kter I appreciate your enthusiasm for the 2.0 release, there is a lot of great improvements in it. But unfortunately, it does not yet cover the use case that @petefoth describes: 2.0 does __not__ support unattended app updates for Android versions less than 12. 

As it stands right now, F-Droid 2.0 does not support FPE.  Improved FPE and full support is on our roadmap (https://gitlab.com/fdroid/privileged-extension/-/work_items/100).  We should know more in a month or two.

**Comment by petefoth** [comment]
Thanks @eighthave 
In that case I think the way forward for us is
1. Continue shipping 1.n client in our builds;
2. Continue shipping FPE;
3. Advise users of our 18.1 builds not to update to client 2.0 unless they are happy to lose the automatic, unattended updates feature.

That should work, at least until 2.0 becomes the suggested non-beta version. If the issue is not resolved by then we will advise users of our 18.1 builds to disable all updates for F-Droid unless they are happy to lose the automatic, unattended updates feature.

Thanks again.
